name: Unit tests

on:
  push: ~
  pull_request: ~
  schedule:
    -
      cron: "0 1 * * 6" # Run at 1am every Saturday
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-22.04
    name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, Sylius ${{ matrix.sylius }}"
    strategy:
      fail-fast: false
      matrix:
        php: ["8.0", "8.1"]
        symfony: ["^5.4", "^6.0"]
        sylius: ["~1.10.14", "~1.11.10", "~1.12.0"]

        exclude:
          -
            php: "8.1"
            sylius: "~1.10.14"

          -
            symfony: "^6.0"
            sylius: "~1.10.14"

          -
            symfony: "^6.0"
            sylius: "~1.11.10"

    steps:
      -
        uses: actions/checkout@v2

      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      -
        name: Restrict Symfony and Sylius versions
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins "symfony/flex"
          composer config extra.symfony.require "${{ matrix.symfony }}"
          composer require "sylius/sylius:${{ matrix.sylius }}" --no-update --no-scripts --no-interaction
      -
        name: Install dependencies
        run: composer update --no-scripts

      -
        name: Run tests
        run: vendor/bin/phpunit
